spring:
  application:
    name: config-service
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Ballouk12/excellia_config.git
          default-label: master

server:
  port: 9998

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"



