spring:
  application:
    name: discovery-service  # Utilisation du tiret au lieu du souligné pour la convention de nommage standard


  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # Le serveur Eureka ne s'enregistre pas lui-même
    fetch-registry: false  # Il ne récupère pas non plus la liste des services
